export const GET_POKEDATA = "GET_POKEMON_DATA";
export const GET_DATA_SUCCESS = "GET_REQUEST_SUCCESS";
export const CHANGE = "CHANGE_LIST_POKEMONS";
export const GET_POKEMON = "GET_POKEMON";
export const GET_POKEMON_SUCCESS = "GET_POKEMON_SUCCESS";
export const GET_REQUEST_FAILURE = "GET_REQUEST_FAILURE";
